### ISSUE TITLE
All tests running all the time

### ISSUE THREAD

**Issue by marclazell** [ferstl/junit-testgroups#2]
My setup:
```
@TestGroup("common")
public class BillingDayServiceImplTest extends JooqTest {
    @ClassRule
    public static TestGroupRule rule = new TestGroupRule();
    public BillingDayServiceImpl target;
```

Maven intellij config: clean install -Dtestgroup=authorisation

But BillingDayServiceImplTest still runs and shouldn't as far as I can tell!

**Comment by ferstl** [comment]
I'll have a look

**Comment by marclazell** [comment]
thank you, if you need more information please let me know.

**Comment by ferstl** [comment]
@marclazell I can not reproduce your problem. I created this Test based on your example:

    import org.junit.ClassRule;
    import org.junit.Test;
    import com.github.ferstl.junit.testgroups.TestGroup;
    import com.github.ferstl.junit.testgroups.TestGroupRule;
    
    @TestGroup("common")
    public class BillingDayServiceImplTest {

      @ClassRule
      public static TestGroupRule rule = new TestGroupRule();
    
      @Test
      public void test() {}
    }

When I run `mvn clean install -Dtestgroup=authorisation` the test is skipped:

    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running BillingDayServiceImplTest
    Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.052 sec
    
    Results :
    
    Tests run: 1, Failures: 0, Errors: 0, Skipped: 1


What is in your base class `JooqTest`? Are you using a test runner that is not part of JUnit?

**Comment by marclazell** [comment]
```
@RunWith(SpringJUnit4ClassRunner.class)
@TestExecutionListeners({DependencyInjectionTestExecutionListener.class})
@ContextConfiguration(locations = "classpath:testjooq.xml")
public abstract class JooqTest {
```

And a few Mocks and things.

Does your framework work for SpringForJunit?

**Comment by ferstl** [comment]
@marclazell There is indeed an issue with `SpringJUnit4ClassRunner`. With an inactive test group your test will not be executed. However, the test runner will setup everything else. For example, it will create an Application context, inject dependencies, etc. before it finds out that there is nothing to do.
The reason for this behaviour is that all these steps happen before any JUnit class rules (such as `TestGroupRule`) are triggered.

Since Spring version 4.2, there is a solution to this problem. This version introduced [class and method rules](http://docs.spring.io/spring/docs/4.2.4.RELEASE/spring-framework-reference/htmlsingle/#testcontext-junit4-rules) as replacement for the `SpringJUnit4ClassRunner`.

So if you are already using Spring 4.2, you can use a `RuleChain` which runs the `TestGroupRule` as the first rule:

    @ClassRule
    public RuleChain rules = RuleChain
        .outerRule(new TestGroupRule())
        .around(new SpringClassRule());

Instead of `SpringJUnit4ClassRunner`, you can just use JUnits `BlockJUnit4ClassRunner` which is the default if you don't use the `@RunWith` annotation.

**Comment by marclazell** [comment]
@ferstl Thank you for this answer. Is there any solution to this issue where I can use SpringJUnit4ClassRunner with your TestGroup framework? The tests were written by a third party and I am unsure of the impact of changing the runner on thousands of tests.

Thanks!

**Comment by ferstl** [comment]
@marclazell Unfortunately, there is nothing I can do. The `SpringJUnit4ClassRunner` creates the application context before any of the JUnit test rules are evaluated.

What I saw is, that the test runner just creates the application context but does not instantiate any beans (at least in my example). So probably, there is not much overhead for tests that do not run because of the `TestGroupRule`. If this doesn't work for you, you may try Spring's {{@IfProfileValue}} annotation instead of {{@TestGroup}}. I don't have much experience with this spring feature, but you could probably use {{@TestGroup}} for non-Spring tests and {{@IfProfileValue}} for Spring tests together.

**Comment by marclazell** [comment]
Okay thanks very much for the advice! I will consult one of our architects about this dilemma as we really want to group tests, and your framework is quite easy and lightweight!

thanks again! Closing issue!
